name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - develop  # Add other branches if needed

jobs:
  lint-and-test:
    name: Run Linting & Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Linting
        run: npm run lint

      - name: Run Tests
        run: npm test
